name: Initial Load of Chart of Accounts

on:
  # Ejecutar manualmente
  workflow_dispatch:

jobs:
  load-accounts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas psycopg2-binary
      
      - name: Run load script
        env:
          SUPABASE_DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
          SUPABASE_DB_USER: ${{ secrets.SUPABASE_DB_USER }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_DB_PORT: ${{ secrets.SUPABASE_DB_PORT }}
          HOLDED_API_KEY: ${{ secrets.HOLDED_API_KEY }}
        run: python code/bronze/holded_chart_accounts_load.py
