name: Load Silver Layer

on:
  # Ejecutar automáticamente después de actualizar Bronze
  workflow_run:
    workflows: ["Update Holded Chart of Accounts", "Update Holded Daily Ledger"]
    types:
      - completed
  
  # También permitir ejecución manual
  workflow_dispatch:
    inputs:
      tables:
        description: 'Tablas a cargar (accounts,fiscal_periods,journal_entries,journal_lines,account_balances)'
        required: false
        default: ''
      full_refresh:
        description: 'Realizar refresco completo'
        type: boolean
        required: false
        default: false

jobs:
  load-silver:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy psycopg2-binary
      
      - name: Load Silver Layer
        env:
          SUPABASE_DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
          SUPABASE_DB_USER: ${{ secrets.SUPABASE_DB_USER }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_DB_PORT: ${{ secrets.SUPABASE_DB_PORT }}
          SUPABASE_DB_NAME: ${{ secrets.SUPABASE_DB_NAME || 'postgres' }}
        run: |
          python code/silver/load_silver.py ${{ inputs.full_refresh && '--full-refresh' || '' }} ${{ inputs.tables && format('--tables={0}', inputs.tables) || '' }}
